create database sqlcasestudy
GO;
use sqlcasestudy
GO;

select * from fact;
select * from Location;
select * from Product;

/*Display the number of states present in the LocationTable.*/
select count(distinct(state)) no_of_states
from Location;

/*How many products are of regular type?*/
select count(ProductId) regular_product_count
from Product
where Type = 'Regular';

--How much spending has been done on marketing of product ID 1?
select ProductId,Sum(Marketing) as spent_on_marketing
from fact
where ProductId = 1
group by ProductId;

--What is the minimum sales of a product?
select ProductId,MIN(sales) min_sales
from fact
group by ProductId
order by ProductId;

--. Display the max Cost of Good Sold (COGS).
select MAX(COGS) max_cogs
from fact;

--Display the details of the product where product type is coffee
select * from Product
where Product_Type='coffee';

--Display the details where total expenses are greater than 40.
select * from fact
where Total_Expenses > 40;

--What is the average sales in area code 719?
select AVG(Sales) avg_sales from fact
where Area_Code = 719;

--Find out the total profit generated by Colorado state.
select SUM(Profit) total_profit
from fact f
INNER JOIN Location l
ON f.Area_Code = l.Area_Code
where State= 'Colorado';

--Display the average inventory for each product ID.
select ProductId,AVG(Inventory) avg_inventory
from fact
group by ProductId
order by ProductId;

--Display state in a sequential order in a Location Table
select DISTINCT 
	State 
from Location
order by State;

--Display the average budget of the Product where the average budget
--margin should be greater than 100.
select ProductId,AVG(Budget_Sales) avg_budget from fact 
group by ProductId
Having AVG(Budget_Margin) > 100
order by avg_budget;

--What is the total sales done on date 2010-01-01?
select SUM(Sales) total_sales
from fact
where Date = '2010-01-01';

--Display the average total expense of each product ID on an individual date
select ProductId,Date,AVG(Total_Expenses) avg_total_expenses
from fact
group by ProductId,Date
order by ProductId,Date;

--Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code
select DATE,p.ProductId,p.Product_Type,p.Product,f.Sales,f.Profit,l.State,l.Area_Code
from fact f
INNER JOIN Product p ON
f.ProductId = p.ProductId
INNER JOIN Location l ON
f.Area_Code = l.Area_Code

--Display the rank without any gap to show the sales wise rank.
select 
Sales, 
DENSE_RANK() OVER(
				order by Sales desc)
from fact

/*Find the state wise profit and sales.*/
select 
	l.State,
	SUM(f.Profit) total_profit,
	SUM(f.Sales) total_sales
from Location l
LEFT JOIN fact f ON
l.Area_Code = f.Area_Code
group by l.State 
order by l.State 

/*Find the state wise profit and sales along with the productname.*/
select 
	p.Product,
	l.State,
	SUM(f.Profit) total_profit,
	SUM(f.Sales) total_sales
from Location l
LEFT JOIN fact f ON
l.Area_Code = f.Area_Code
LEFT JOIN Product p ON
f.ProductId = p.ProductId
group by l.State,p.Product
order by l.State,p.Product
/*If there is an increase in sales of 5%, calculate the increasedsales.*/
select
	p.Product,
	SUM(f.Sales) total_sales,
	SUM(f.Sales) * 1.05 increased_sales
from fact f
Left Join Product p ON
f.ProductId = p.ProductId
group by p.Product
order by p.Product
/*Find the maximum profit along with the product ID and producttype*/
select 
	p.ProductId,
	p.Product_Type,
	MAX(f.Profit) max_profit
from Product p
Left join fact f on
p.ProductId = f.ProductId
group by p.ProductId,p.Product_Type
/*Create a stored procedure to fetch the result according to the product typefrom Product Table.*/
CREATE PROCEDURE sp_GetProductByProductType(@product_type VARCHAR(50))
AS
BEGIN
	select *
	from Product
	where Product_Type = @product_type
END;
EXEC sp_GetProductByProductType 'Espresso'
/*Write a query by creating a condition in which if the total expenses is lessthan60 then it is a profit or else loss.*/
Select
	ProductId,
	Total_expenses,
	CASE 
		WHEN Total_Expenses < 60 THEN 'Profit'
		ELSE 'Loss'
	END AS PROFITorLOSS
from fact
order by ProductId

/*Give the total weekly sales value with the date and product IDdetails. Useroll-up to pull the data in hierarchical order*/

Select
	DATEPART(WEEK,Date) Sales_week,
	Date,
	ProductId,
	SUM(Sales) weekly_sales
from fact 
group by
	rollup(
	DATEPART(WEEK,Date),
	Date,
	ProductId
	)
order by 
DATEPART(WEEK,Date) ,
	Date,
	ProductId

/*Apply union and intersection operator on the tables which consist of
attribute area code.*/
select 
	Area_Code
from fact

UNION

select 
	Area_Code 
from Location
order by Area_Code;

(select 
	Area_Code
from fact

INTERSECT

select 
	Area_Code 
from Location)
order by Area_Code;
/*Create a user-defined function for the product table to fetch a particular
product type based upon the user’s preference.*/

CREATE FUNCTION dbo.udfProductType
(
	@productType VARCHAR(50)
)
RETURNS TABLE
AS

RETURN(
	select * from Product
	where Product_Type = @productType
	)

select * from dbo.udfProductType('Coffee');


/*Change the product type from coffee to tea where product IDis 1 andundoit.*/
BEGIN TRANSACTION

UPDATE Product
SET Product_Type = 'Tea'
WHERE ProductId = 1

select * from Product 
where ProductId = 1

ROLLBACK TRANSACTION
/*Display the date, product ID and sales where total expenses are
between 100 to 200.*/

select * from Product;
select * from fact;
select * from Location;

select
	Date,
	ProductId,
	Sales,
	Total_Expenses
from fact
where Total_Expenses BETWEEN 100 AND 200
order by Total_Expenses DESC;
/*Delete the records in the Product Table for regular type.*/

DELETE FROM Product
where Type = 'Regular'

/*Display the ASCII value of the fifth character from the columnProduct.*/

select 
	Product,
	SUBSTRING(Product,5,1) fifthcharacter,
	ASCII(SUBSTRING(Product,5,1)) ASCII_VALUE
from Product